manifest:
  remotes:
    - name: zmkfirmware-arqubusier
      url-base: https://github.com/arqubusier
  projects:
    - name: zmk
      remote: zmkfirmware-arqubusier
      revision: grapto_v3w
      import: app/west.yml
  self:
    path: config
