manifest:
  remotes:
    - name: zmkfirmware-arqubusier
      url-base: https://github.com/arqubusier
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
